name: Push

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.13", "1.14", "1.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Uses go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: make build
      - name: Test
        run: make test
