name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Uses go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
      - name: Build
        run: make build
      - name: Test
        run: make test
